#!/bin/sh

if [ ! -f configure ]; then
    echo "Autogening..."
    ./autogen.sh
fi

prefix="/usr/local/Emacs"
mkdir $prefix

./configure --prefix="$prefix" --with-modules --with-ns || exit

make clean || exit
make -j4 || exit
make -j2 install || exit

rm -rf /Applications/Emacs.app
cp -r nextstep/Emacs.app /Applications/Emacs.app
ln -s /Applications/Emacs.app/Contents/MacOS/bin/emacsclient /usr/local/bin


echo "Emacs build finished."
