#!/bin/sh

if [ ! -f configure ]; then
    echo "Autogening..."
    ./autogen.sh
fi

prefix="/usr/local/Emacs"
mkdir $prefix

./configure --prefix="$prefix" --with-modules --with-ns --disable-ns-self-contained || exit

make clean || exit
make -j4 || exit
make -j2 install || exit

cp -r nextstep/Emacs.app /Applications/Emacs.app

rm $prefix/bin/emacs
cat <<EOF > $prefix/bin/emacs
#!/bin/bash
exec /Applications/Emacs.app/Contents/MacOS/Emacs -nw "\$@"
EOF
chmod a+x $prefix/bin/emacs

echo "Emacs build finished."
