#!/usr/bin/env bash

opt_dir="$(brew --prefix openssl):$(brew --prefix readline):$(brew --prefix libyaml):$(brew --prefix gdbm)"

name=${1:-"$(basename $PWD)"}
install_dir="$HOME/.rubies/$name/"

echo "configuring on $install_dir"
[ -f ./configure ] || autoconf
./configure --prefix="$install_dir" "${opt_dir:+--with-opt-dir="$opt_dir"}"

echo "making..."
make -j

echo "installing..."
make install
