name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request: []
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: Validate syntax
      run: find . -name '*.sh' -exec bash -n {} \;

    - name: Test script/setup
      run: bash script/setup

    - name: Test bashrc
      run: bash -xc "source ~/.bashrc"

    - name: Test zshrc
      run: zsh -xc "source ~/.zshrc"
      if: matrix.os == 'macos-latest'
